### ISSUE TITLE
Test-run needed: f-Find-Overlapping-Landsat-Scenes-TEST.ipynb

### ISSUE THREAD

**Issue by sarahmjaffe** [kessb/sagebrush-ecosystem-modeling#11]
@kessb This simplified code will retrieve the url associated with specified Landsat scenes.  
1) Can you please check to see if it runs on your end?  It should run with any NEON site.
2) We need to discuss if we want it to download all possible scenes in the background (as workflow originally intended), since we'll likely use figshare files to condense blog run time.

**Comment by kessb** [comment]
Code has been tested and is reproducible.

**Comment by sarahmjaffe** [comment]
@kessb Great news!  Thanks!  Fix #11
