### ISSUE TITLE
manually extracting endmembers throwing np.nan error

### ISSUE THREAD

**Issue by kessb** [kessb/sagebrush-ecosystem-modeling#6]
@sarahmjaffe could you take a look at this? After header " Estimate number of materials present in scene", I'm getting an error when I try to run 
neon_shp = neon_sub_cube.values.shape
est_num_mats = HfcVd(neon_sub_cube.values.reshape(neon_shp[0]*neon_shp[1], neon_shp[2]), far='default')
est_num_mats
The original error is printed below that cell. I added two cells above to see if I could clean the array, but haven't found a way without changing the array dimensions.
NaNs also throwing error for auto-extraction of endmembers (code after the next header)

**Comment by sarahmjaffe** [comment]
@kessb Maybe it's in here somewhere, but can you please tell me which notebook this code is in?  I can't seem to find it in either of your hyperspectral test notebooks.  Thanks!

**Comment by kessb** [comment]
Pursuing alternate workflow
