### ISSUE TITLE
spectral libraries

### ISSUE THREAD

**Issue by kessb** [kessb/sagebrush-ecosystem-modeling#7]
spectral signatures need to be downloaded (or accessed via API) for:
cheatgrass
sagebrush
soil
water
and optionally a native grass
These should translate to both NEON and LANDSAT data and be from the same instrument or an average of instrument readings

**Comment by kessb** [comment]
Would you mind selecting the files? I figure it's easier for one person to do this. If you can't find measurements from the same instrument, lmk and we can split this up.

**Comment by sarahmjaffe** [comment]
@kessb Spectral signatures for sagebrush and cheatgrass were positively identified for both Landsat and AVIRIS/NEON.  Water signatures need review.  Further discussion of signatures needed.  All signatures collected can be found on figshare project invite sent 6/20/2020. Fixes #7
